g_conf = {
    'osd_dir': '/export/.osd_meta_config',
    'swift_dir': '/etc/swift',
    'object_post_as_copy': 'false',
    'node_timeout': 10,
    'conn_timeout': 0.5,
    'client_timeout': 60,
    'retry_count': 3,
    'object_chunk_size': 65536,
    'client_chunk_size': 65536,
    'trans_id_suffix': '',
    'post_quorum_timeout': 0.5,
    'recheck_container_existence': 60,
    'recheck_account_existence': 60,
    'allow_account_management': 'no',
    'max_containers_per_account': 10000000,
    'bind_port': 61005,
    'llport': 61014,
    'max_bulk_delete_entries': 1000
}
